config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students
  resources :classrooms, only: [:create, :new]

  root 'courses#index'
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  validates :student, :course, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  has_many :students, :through => :classrooms

  validates :name, :description, :status, presence: true

  has_enumeration_for :status, create_helpers: true, create_scopes: true
end

app/models/status.rb
class Status < EnumerateIt::Base
  associate_values active: 0, inative: 1
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms
  has_many :courses, :through => :classrooms

  validates :name, :status, presence: true
  before_create :generate_register

  has_enumeration_for :status, create_helpers: true, create_scopes: true
  private

    def generate_register
      self.register_number = SecureRandom.hex(6)
      generate_register if Student.exists?(register_number: self.register_number)
    end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  respond_to :html

  def create
    @classroom = Classroom.find_or_initialize_by(classroom_params)
    if @classroom.save
      @student = @classroom.student
      flash[:notice] = t('flash.classrooms.create')
      redirect_to @student
    else
      render :new
    end
  end

  def new
    @classroom = Classroom.new
  end

  private
    def classroom_params
      params.require(:classroom).permit(:student_id, :course_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @students = Student.all
    respond_with(@students)
  end

  def show
    respond_with(@student)
  end

  def new
    @student = Student.new
    respond_with(@student)
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    @student.save
    respond_with(@student)
  end

  def update
    @student.update(student_params)
    respond_with(@student)
  end

  def destroy
    @student.destroy
    respond_with(@student)
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/views/classrooms/new.html.slim
- content_for(:subtitle) do
  = t('.title')

= simple_form_for(@classroom, html: { class: 'pure-form pure-form-stacked' }, validate: true) do |f|
  = f.error_notification

  = f.input :student_id, collection: Student.active
  = f.input :course_id, collection: Course.active

  = f.button :submit, class: 'pure-button'

app/views/courses/_form.html.slim
= simple_form_for(@course, html: { class: 'pure-form pure-form-stacked' }, validate: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :status, collection: Status.to_a

  .form-actions
    = f.button :submit

app/views/courses/_students.html.slim
table.center.pure-table
  thead
    tr
      th= t('simple_form.labels.defaults.name')
      th= t('simple_form.labels.defaults.register_number')
      th Status

  tbody
    - students.each do |student|
      tr
        td = link_to student.name, student
        td = student.register_number
        td = student.status_humanize

app/views/courses/edit.html.slim
- content_for(:subtitle) do
  = t('.title')

== render 'form'

= link_to t('defaults.models.show'), @course
'|
= link_to t('defaults.models.back'), courses_path

app/views/courses/index.html.slim
- content_for(:subtitle) do
  = t('.title')

table.center.pure-table
  thead
    tr
      th= t('simple_form.labels.defaults.name')
      th= t('simple_form.labels.defaults.description')
      th Status

  tbody
    - @courses.each do |course|
      tr
        td = link_to course.name, course
        td = course.description
        td = course.status_humanize

br

.btn-group
  = link_to t('courses.new.link'), new_course_path, class: 'pure-button'

app/views/courses/new.html.slim
- content_for(:subtitle) do
   = t('.title')

== render 'form'

= link_to t('defaults.models.back'), courses_path

app/views/courses/show.html.slim
p#notice = notice
- content_for(:subtitle) do
  = @course.name

p
  strong= t('simple_form.labels.defaults.name')
  | : 
  = @course.name
p
  strong= t('simple_form.labels.defaults.description')
  | : 
  = @course.description
p
  strong Status:
  = @course.status_humanize

- if @course.students.any?
  h2= t('courses.students.title')

  = render partial: 'students', locals: { students: @course.students }

= link_to t('courses.edit.link'), edit_course_path(@course)

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Scholl
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #layout
      a#menuLink.menu-link href="#menu"
        span
      #menu
        .pure-menu
          a.pure-menu-heading href="#"  Escola
          ul.pure-menu-list
            li.pure-menu-item
              = link_to t('students.index.title'), students_path,
                class: 'pure-menu-link'
            li.pure-menu-item
              = link_to t('courses.index.title'), courses_path,
                class: 'pure-menu-link'
            li.pure-menu-item
              = link_to t('classrooms.new.title'), new_classroom_path,
                class: 'pure-menu-link'
      #main
        .header
          h1 Escola
          h2= yield(:subtitle)
        .content
          = yield

app/views/students/_courses.html.slim
table.center.pure-table
  thead
    tr
      th= t('simple_form.labels.defaults.name')
      th= t('simple_form.labels.defaults.description')
      th Status

  tbody
    - courses.each do |course|
      tr
        td = link_to course.name, course
        td = course.description
        td = course.status_humanize

br

app/views/students/_form.html.slim
= simple_form_for(@student, html: { class: 'pure-form pure-form-stacked' }, validate: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :status, collection: Status.to_a

  .form-actions
    = f.button :submit, class: 'pure-button pure-button-primary'

app/views/students/edit.html.slim
- content_for(:subtitle) do
  = t('.title')

== render 'form'

= link_to t('defaults.models.show'), @student
'|
= link_to t('defaults.models.back'), students_path

app/views/students/index.html.slim
- content_for(:subtitle) do
  = t('.title')

table.center.pure-table
  thead
    tr
      th= t('simple_form.labels.defaults.name')
      th= t('simple_form.labels.defaults.register_number')
      th Status

  tbody
    - @students.each do |student|
      tr
        td = link_to student.name, student
        td = student.register_number
        td = student.status_humanize

br

.btn-group
  = link_to t('students.new.link'), new_student_path, class: 'pure-button'

app/views/students/new.html.slim
- content_for(:subtitle) do
  = t('.title')

== render 'form'

= link_to t('defaults.models.back'), students_path

app/views/students/show.html.slim
- content_for(:subtitle) do
  = @student.name
p#notice = notice

p
  strong= t('simple_form.labels.defaults.name')
  | : 
  = @student.name
p
  strong= t('simple_form.labels.defaults.register_number')
  | : 
  = @student.register_number
p
  strong Status:
  = @student.status_humanize

- if @student.courses.any?
  h2= t('students.courses.title')

  = render partial: 'courses', locals: { courses: @student.courses }


= link_to t('defaults.models.edit'), edit_student_path(@student)